services:
  kutt:
    build: .
    container_name: kutt
    restart: always
    mem_limit: 512m
    expose: [3000/tcp]
    env_file: .env
    volumes:
      - ~/apps/kutt/db:/kutt/db
    networks:
      - caddy

networks:
  caddy:
    external: true
